name: Server Startup Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-server-startup:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Test server startup
      run: npm run test:startup
      
    - name: Verify server can start without Neovim
      run: |
        echo "Testing server startup with an invalid socket path"
        # Use an invalid socket path that definitely won't exist
        NON_EXISTENT_SOCKET="/tmp/non-existent-socket-$(date +%s)"
        
        # Start the server with a timeout to automatically kill it after 5 seconds
        timeout 5s node dist/index.js $NON_EXISTENT_SOCKET 2>&1 | tee server_output.log || true
        
        # Check that the server started but couldn't connect to Neovim (expected behavior)
        if grep -q "Neovim MCP Server running on stdio WITHOUT Neovim connection" server_output.log; then
          echo "✅ Server started successfully without Neovim connection"
          exit 0
        else
          echo "❌ Server failed to start properly without Neovim"
          cat server_output.log
          exit 1
        fi
